import React from 'react';

function AboutContent() {
  return (
    <div className="container">
      
      <h3>About the Content</h3>

      <p>This website is dedicated to providing educational information about the dangers of smoking.</p>

      <p>The content you see is generated by an AI model trained on specialized datasets related to smoking and health, including scientific publications, public health reports, and verified medical sources.</p>

      <p>Each fact on the site is accompanied by short contextual hints that guide you toward new, related information. These hints create a unique interactive experience, allowing you to explore the topic dynamically and intuitively.</p>

      <p>All generated texts aim to be clear, concise, and informative. The goal is to raise awareness, support people who want to quit smoking, and offer valuable insights without overwhelming the reader.</p>

      <p>Please note that while AI helps structure and personalize the content, the foundation remains scientific and evidence-based. However, this website is not a substitute for medical advice. If you need help quitting smoking, consult a healthcare professional.</p>

    </div>
  );
}

export default AboutContent;
