import React from 'react';

function AboutProject() {
  return (
    <div className="container-text-about">
      <h1>About the project</h1>
      <h3>Hello everyone!</h3>
      <p>I started smoking in 2011, and since then, I've quit and relapsed many times. It has been an ongoing battle with myself. At one point, I believed smoking was a good way to take a break at work, kill time while waiting, or even start a conversation with another smoker. However, this habit has significant downsides: addiction, health problems, and substantial financial costs.</p>
      <p>Each morning used to begin with a cigarette. Before lunchtime, I would smoke at least five times: right after waking up, before leaving home, upon arriving at work, and then approximately every hour. I needed a cigarette roughly every hour, and if I couldn't smoke, I became irritable. Many smokers know this feeling—the constant craving for a cigarette is relentless.</p>
      <p>Think about how much time and money we spend smoking, not to mention the harm to our health. Assuming I sleep 8 hours a day, that leaves 16 hours awake. On average, I smoked a cigarette every hour. Each cigarette took about 5 to 10 minutes (including the time spent reaching a smoking area and other minor tasks). This totals around 120 minutes (two hours) a day, 60 hours per month, and an astonishing 720 hours per year! That’s the equivalent of an entire month spent exclusively on smoking, without breaks for eating or sleeping! More than 12% of my waking hours and about 10% of my income went to cigarettes. It's like working one month solely to afford cigarettes and then spending another month smoking them. Imagine how costly this habit is for an average person! Additionally, future medical expenses related to smoking-related diseases could be even higher.</p>
      <p>Imagine what else you could do with these 60 hours per month! You could read books or articles, exercise, meditate, handle important tasks, or learn new skills. The money saved could be invested in education, gym memberships, or improving your diet.</p>
      <p>Recently, I decided to support myself in my battle against addiction by creating a project dedicated to quitting smoking. I'm not a programmer or a web designer, but artificial intelligence came to my aid. Using ChatGPT, I independently completed the entire cycle of website creation: frontend development with React, backend with Python, and integration with the OpenAI API. It was an incredible experience, as I knew very little about website creation or programming. Throughout the process, I realized that artificial intelligence can bring ideas to life even in unfamiliar fields.</p>
      <p>The website functionality is straightforward: you see text generated by an AI model trained on specialized data about the dangers of smoking. Below the text are three contextual hints; clicking on them provides new thematic content. There are also buttons to view a new fact (on the right) or the previous one (on the left). In the bottom right corner, there's a navigation menu to revisit facts you've already read.</p>
      <p>I hope these anti-smoking facts help you in your battle against this harmful habit.</p>
      <p><strong><em>Feel free to connect with me on social media X:</em></strong> <a href="https://x.com/bred_twitt">https://x.com/bred_twitt</a></p>
    </div>
  );
}

export default AboutProject;
